/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SummonerIndexImport } from './routes/summoner/index'
import { Route as SummonerRegionIndexImport } from './routes/summoner/region.index'
import { Route as SummonerRegionIdImport } from './routes/summoner/$region.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerIndexRoute = SummonerIndexImport.update({
  path: '/summoner/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerRegionIndexRoute = SummonerRegionIndexImport.update({
  path: '/summoner/region/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerRegionIdRoute = SummonerRegionIdImport.update({
  path: '/summoner/$region/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/summoner/': {
      id: '/summoner/'
      path: '/summoner'
      fullPath: '/summoner'
      preLoaderRoute: typeof SummonerIndexImport
      parentRoute: typeof rootRoute
    }
    '/summoner/$region/$id': {
      id: '/summoner/$region/$id'
      path: '/summoner/$region/$id'
      fullPath: '/summoner/$region/$id'
      preLoaderRoute: typeof SummonerRegionIdImport
      parentRoute: typeof rootRoute
    }
    '/summoner/region/': {
      id: '/summoner/region/'
      path: '/summoner/region'
      fullPath: '/summoner/region'
      preLoaderRoute: typeof SummonerRegionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SummonerIndexRoute,
  SummonerRegionIdRoute,
  SummonerRegionIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/summoner/",
        "/summoner/$region/$id",
        "/summoner/region/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/summoner/": {
      "filePath": "summoner/index.tsx"
    },
    "/summoner/$region/$id": {
      "filePath": "summoner/$region.$id.tsx"
    },
    "/summoner/region/": {
      "filePath": "summoner/region.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
